# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: genui_monorepo
publish_to: none
license: BSD-3-Clause

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7 <4.0.0"

workspace:
  - examples/catalog_gallery
  - examples/custom_backend
  - examples/simple_chat
  - examples/simple_chat_controller
  - examples/travel_app
  - examples/verdure/client
  - packages/genui
  - packages/genui_a2ui
  - packages/genui_a2ui/example
  - packages/genui_dartantic
  - packages/genui_dartantic/example
  - packages/genui_firebase_ai
  - packages/genui_google_generative_ai
  - packages/json_schema_builder
  - tool/fix_copyright
  - tool/release
  - tool/test_and_fix

flutter:
  uses-material-design: true
