# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: genui
description: Generates and displays generative user interfaces (GenUI) in Flutter using AI.
version: 0.7.0
homepage: https://github.com/flutter/genui/tree/main/packages/genui
license: BSD-3-Clause
issue_tracker: https://github.com/flutter/genui/issues

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7 <4.0.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  genai_primitives: ^0.2.0
  intl: ^0.20.2
  json_schema_builder: ^0.1.3
  logging: ^1.3.0
  meta: ^1.17.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  uuid: ^4.4.0

dev_dependencies:
  async: ^2.13.0
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
  test: ^1.26.2
